--Gets user activity data
WITH days_data AS (
    SELECT USER_ID,
    	PLAYER_START_DATE AS installDate,
    	EVENT_DATE 	
	FROM account_fact_user_sessions_day
	WHERE PLAYER_START_DATE >= CURRENT_DATE - 30
    	AND ENVIRONMENT_ID = [YOUR TARGET ENVIRONMENT]
	GROUP BY USER_ID, PLAYER_START_DATE, EVENT_DATE
)

--Counts user retention
SELECT installDate, 
    NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 0 THEN USER_ID ELSE NULL END)) AS "installs",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 1 THEN USER_ID ELSE NULL END)) AS "1",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 2 THEN USER_ID ELSE NULL END)) AS "2",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 3 THEN USER_ID ELSE NULL END)) AS "3",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 4 THEN USER_ID ELSE NULL END)) AS "4",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 5 THEN USER_ID ELSE NULL END)) AS "5",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 6 THEN USER_ID ELSE NULL END)) AS "6",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 7 THEN USER_ID ELSE NULL END)) AS "7",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 8 THEN USER_ID ELSE NULL END)) AS "8",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 9 THEN USER_ID ELSE NULL END)) AS "9",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 10 THEN USER_ID ELSE NULL END)) AS "10",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 11 THEN USER_ID ELSE NULL END)) AS "11",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 12 THEN USER_ID ELSE NULL END)) AS "12",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 13 THEN USER_ID ELSE NULL END)) AS "13",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 14 THEN USER_ID ELSE NULL END)) AS "14",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 21 THEN USER_ID ELSE NULL END)) AS "21",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - installDate = 30 THEN USER_ID ELSE NULL END)) AS "30"
FROM days_data
WHERE CURRENT_DATE - EVENT_DATE BETWEEN 0 AND 30
GROUP BY 1
ORDER BY 1 DESC