WITH days_data AS (
    SELECT USER_ID,
    PLAYER_START_DATE AS install_date,
    EVENT_DATE 	
	FROM account_fact_user_sessions_day
	WHERE PLAYER_START_DATE >= CURRENT_DATE - 30
    AND ENVIRONMENT_ID = [YOUR TARGET ENVIRONMENT]
	GROUP BY USER_ID, PLAYER_START_DATE, EVENT_DATE
)

SELECT install_date, 
    NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 0 THEN USER_ID ELSE NULL END)) AS "installs",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 1 THEN USER_ID ELSE NULL END)) AS "1",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 2 THEN USER_ID ELSE NULL END)) AS "2",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 3 THEN USER_ID ELSE NULL END)) AS "3",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 4 THEN USER_ID ELSE NULL END)) AS "4",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 5 THEN USER_ID ELSE NULL END)) AS "5",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 6 THEN USER_ID ELSE NULL END)) AS "6",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 7 THEN USER_ID ELSE NULL END)) AS "7",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 8 THEN USER_ID ELSE NULL END)) AS "8",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 9 THEN USER_ID ELSE NULL END)) AS "9",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 10 THEN USER_ID ELSE NULL END)) AS "10",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 11 THEN USER_ID ELSE NULL END)) AS "11",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 12 THEN USER_ID ELSE NULL END)) AS "12",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 13 THEN USER_ID ELSE NULL END)) AS "13",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 14 THEN USER_ID ELSE NULL END)) AS "14",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 21 THEN USER_ID ELSE NULL END)) AS "21",
	NULLIFZERO (COUNT (DISTINCT CASE WHEN EVENT_DATE - install_date = 30 THEN USER_ID ELSE NULL END)) AS "30"
FROM days_data
	WHERE CURRENT_DATE - EVENT_DATE BETWEEN 0 AND 30
GROUP BY 1
ORDER BY 1 DESC