SELECT DATE_PART('hour', EVENT_TIMESTAMP) AS localHour, 
    COUNT(DISTINCT USER_ID) AS UniqueUsers
FROM account_events
WHERE ENVIRONMENT_ID = [YOUR TARGET ENVIRONMENT]
GROUP BY localHour
ORDER BY localHour